services:
  - type: web
    name: innovation4albania-backend
    runtime: docker
    plan: free
    rootDir: .
    envVars:
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
